package binom: pipeline;

interface ololo {

  record fff{
    var0: u32,
    name: string,
  }

  record user16 {
    var0: u32,
    var1: bool,
    var2: bool,
    var3: bool,
    var4: bool,
    var5: option<fff>,
    var6: option<string>,
  }
  result-func16: func()-> list<fff>;
  arg-func16: func(aaa:list<fff>);
}

world test {
  import ololo;
  //     import binom:pipeline2/fff;
}
